### PR TITLE
Fix wrongly names dependencies and package name in setup.py

### PR DESCRIPTION
**Pull request by fivepiece**
Running `setup.py install` currently breaks first with :
`error: package directory 'coinswapcs' does not exist`
Then fails to find some dependencies.  This PR fixes the directory structure and the setup file.

  - renamed `coinswap` directory to `coinswapcs`
  - renamed dependency `txjsonrpc` to `txJSON-RPC`
  - renamed dependency `jmclient` to `joinmarketclient`
  - renamed dependency `jmbitcoin` to `joinmarketbitcoin`

Running `python setup.py install` now completes successfuly.

### CODE REVIEW

**Comment by AdamISZ** [comment]
It's almost as if writing a setup file without testing it doesn't work!! ;)

Greatly appreciated, thanks.

**Comment by fivepiece** [comment]
Welcome!  I think I broke it another way though...
`ImportError: No module named coinswap`
Probably need to go over and change that to `coinswapcs` now?

**Comment by fivepiece** [comment]
More incoming in a different PR

**Comment by AdamISZ** [comment]
Sorry only half an eye on this, was going to review later. My instinct would be to keep the directory name as 'coinswap', but would have to double check the right way to do it.

**Comment by AdamISZ** [comment]
Ah, pytest, yeah sorry. What we should do there is make it a try/except on the import error so it's not required for non-testers (and have a requirements_dev.txt or whatever it's called).

**Comment by fivepiece** [comment]
Fair enough, also a couple other imports are needed:
```
diff --git a/coinswap_run.py b/coinswap_run.py
index eee30cd..326acc0 100644
--- a/coinswap_run.py
+++ b/coinswap_run.py
@@ -1,7 +1,8 @@
 #!/home/adam/virtualenvs/escrow/bin/python
 from __future__ import print_function
 import jmbitcoin as btc
-from jmclient import Wallet, estimate_tx_fee, validate_address
+from jmclient import Wallet, WalletError, estimate_tx_fee, validate_address
+from jmbase.support import get_password
 from coinswapcs import (cs_single, CoinSwapPublicParameters, CoinSwapAlice,
                       CoinSwapCarol, CoinSwapJSONRPCClient, sync_wallet,
                       get_current_blockheight, RegtestBitcoinCoreInterface,
```
and eventually we're left with
`2017-04-29 08:32:04,387 [MainThread  ] [INFO ]  BACKOUT: Failure to execute step after: 0, Exception: TypeError("cannot concatenate 'str' and 'int' objects",)
`
I'll close this PR since I agree `coinswap` should be the name and not `coinswapcs`, then re-apply with some saner commits (but if you get to this before I do, please feel free to merge your own!)

**Pull request closed without merging**
